### ISSUE TITLE
Error converting vsi files

### ISSUE THREAD

**Issue by metracy** [pskeshu/microscoper#1]
Hello,

I get the following when I try to run this in terminal on Debian 7 virtual machine

```
python -m microscoper -f . -k .vsi
  0%|                                                                        | 0/165 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/microscoper/__main__.py", line 3, in <module>
    run()
  File "/usr/local/lib/python2.7/dist-packages/microscoper/io.py", line 114, in run
    images = read_images(path)
  File "/usr/local/lib/python2.7/dist-packages/microscoper/io.py", line 74, in read_images
    channel_name = get_channel(path, channel)
  File "/usr/local/lib/python2.7/dist-packages/microscoper/io.py", line 46, in get_channel
    o = bioformats.omexml.OMEXML(meta)
  File "/usr/local/lib/python2.7/dist-packages/bioformats/omexml.py", line 320, in __init__
    self.dom = ElementTree.ElementTree(ElementTree.fromstring(xml))
  File "<string>", line 124, in XML
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb5' in position 612: ordinal not in range(128)

```

**Comment by pskeshu** [comment]
Hi there!

The error has more to do with python-bioformats, which is not able to handle the unicode symbols while reading through the meta data. If you want a simple solution, you can install the fork of `python-bioformats` that I have. Here are the steps:

1. Remove existing `python-bioformats`
`sudo pip uninstall python-bioformats`
2. Clone `pskeshu/python-bioformats`
`git clone https://github.com/pskeshu/python-bioformats.git`
3. Change to `python-bioformats` directory, and switch to `scblab` branch.
`cd python-bioformats`
`git checkout scblab`
4. Install the package with the python version that you are using.
`sudo python setup.py install`

I think this should solve the problem.

**Comment by pskeshu** [comment]
@metracy have a look at the updated [ReadME](https://github.com/pskeshu/microscoper/blob/master/readme.md). And I have pushed a new version just now, so I'd advise a `pip install --upgrade microscoper`. :)

**Comment by metracy** [comment]
Awesome work! I'll check this out tomorrow when I get to the lab. Random I caught you right as you updated it.

**Comment by pskeshu** [comment]
Ah, I was wondering how you might have come across this package! Do spread the word to other IX83/CellSense users who might find this useful. 😄

**Comment by pskeshu** [comment]
@metracy Hi there! The forked `pskeshu/python-bioformats` dependency is no longer required. With `microscoper-0.2.2`, `python-bioformats` from pip will work just fine. Please test this, and let me know!

Edit: `microscoper-0.2.3` has a 10X performance improvement. :)

**Comment by metracy** [comment]
We have a few hundred VSI files and I saw people were manually saving them as tiffs. Google lead me to you ;)

**Comment by metracy** [comment]
so I have the forked version of python-bioformats and the upgraded microscoper and get the following error:

`brain@neurodebian:/media/sf_Z_DRIVE/Shared/DATA/Behavior/test$ python -m microscoper -f . -k .vsi
Failed to get class org/slf4j/Logger
Exception in thread "Thread-0" java.lang.NoClassDefFoundError: org/slf4j/Logger
Caused by: java.lang.ClassNotFoundException: org.slf4j.Logger
	at java.net.URLClassLoader$1.run(URLClassLoader.java:359)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:312)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/microscoper/__main__.py", line 3, in <module>
    run()
  File "/usr/local/lib/python2.7/dist-packages/microscoper/io.py", line 126, in run
    bioformats.init_logger()
  File "/usr/local/lib/python2.7/dist-packages/python_bioformats-1.1.0-py2.7.egg/bioformats/__init__.py", line 94, in init_logger
  File "/usr/local/lib/python2.7/dist-packages/javabridge/jutil.py", line 982, in get_static_field
    raise JavaException(jexception)
javabridge.jutil.JavaException: org/slf4j/Logger
`

**Comment by metracy** [comment]
I uninstalled the forked version and installed the normal version from pip.

Still get the unicode error though with microscoper-0.2.3

`brain@neurodebian:/media/sf_Z_DRIVE/Shared/DATA/Behavior/test$ python -m microscoper -f . -k .vsi
  0%|                                                                                                 | 0/165 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/microscoper/__main__.py", line 3, in <module>
    run()
  File "/usr/local/lib/python2.7/dist-packages/microscoper/io.py", line 132, in run
    images = read_images(path)
  File "/usr/local/lib/python2.7/dist-packages/microscoper/io.py", line 76, in read_images
    metadata = get_metadata(path)
  File "/usr/local/lib/python2.7/dist-packages/microscoper/io.py", line 46, in get_metadata
    metadata = bioformats.omexml.OMEXML(meta)
  File "/usr/local/lib/python2.7/dist-packages/bioformats/omexml.py", line 320, in __init__
    self.dom = ElementTree.ElementTree(ElementTree.fromstring(xml))
  File "<string>", line 124, in XML
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb5' in position 612: ordinal not in range(128)`

**Comment by pskeshu** [comment]
Ah, I'm not sure why it worked in my computer. I suppose you're better off
with the forked version for now. Or you can install the python 3 version of
the packages with python3-pip package, which will work for sure, since
python 3 has Unicode support.

**Comment by metracy** [comment]
ahh okay I will try python3 version.

**Comment by metracy** [comment]
Also thank you for including a python3 version, python2 refuses to die :P

**Comment by pskeshu** [comment]
I've made the shift only recently. Life with python 3 is not so bad now. :D
Do let me know if the package works for you.

**Comment by metracy** [comment]
It looks like the python 3 version is chugging away right now.

`brain@neurodebian:/media/sf_Z_DRIVE/Shared/DATA/Behavior/test$ python3 -m microscoper -f . -k .vsi
  1%|▌                                                                                        | 1/165 [00:02<08:02,  2.94s/it]
C: 100%|████████████████████████████████████████████████████████████████████████████████████████| 2/2 [02:43<00:00, 71.34s/it]
T: 100%|███████████████████████████████████████████████████████████████████████████████████████| 1/1 [01:44<00:00, 104.65s/it]
Z: 100%|███████████████████████████████████████████████████████████████████████████████████████| 1/1 [01:43<00:00, 103.25s/it]
`

**Comment by metracy** [comment]
when I run the command `python -m microscoper -f . -k .vsi` does it put the tiff files in the same directory?

**Comment by metracy** [comment]
I'm running the python3 in a virtual machine and I've got a memory error. I'll try running it on a 16gb laptop when I get home.

`brain@neurodebian:/media/sf_Z_DRIVE/Shared/DATA/Behavior/test$ python3 -m microscoper -f . -k .vsi
Traceback (most recent call last):                                                         | 2/165 [06:16<5:10:05, 114.14s/it]
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main██████████████████████████| 3/3 [03:59<00:00, 78.99s/it]
    "__main__", mod_spec)███████████████████████████████████████████████████████████████████████| 1/1 [01:31<00:00, 91.71s/it]
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code█████████████████████████████████████| 1/1 [01:31<00:00, 91.68s/it]
    exec(code, run_globals)
  File "/usr/local/lib/python3.4/dist-packages/microscoper/__main__.py", line 3, in <module>
    run()
  File "/usr/local/lib/python3.4/dist-packages/microscoper/io.py", line 132, in run
    images = read_images(path)
  File "/usr/local/lib/python3.4/dist-packages/microscoper/io.py", line 92, in read_images
    images[lists] = np.asarray(images[lists])
  File "/usr/local/lib/python3.4/dist-packages/numpy/core/numeric.py", line 531, in asarray
    return array(a, dtype, copy=False, order=order)
MemoryError
`

**Comment by pskeshu** [comment]
@metracy The files are saved in the same directory where the .vsi files are. It should be stored inside a `_filename_` directory for a `filename.vsi` file. Do you require any features? Are there any bugs?

**Comment by pskeshu** [comment]
The latest `python-bioformats` release `v1.2.0` should solve this issue.
