### ISSUE TITLE
hangs on run

### ISSUE THREAD

**Issue by bgriffen** [pskeshu/microscoper#2]
I am trying to convert these files to TIFF from VSI, directory structure is as follows:

```
Cells/
--410c504 D0-091617 D13_Condition1.vsi
--_410c504 D0-091617 D13_Condition1_/stack1/frame_t_0.eps
```

Ideally I would like single channel TIFFs output (grayscale if possible). This is my output:

```
(python2) Cells $python -m microscoper -f .
..._Condition1.vsi:   0%|                                           | 0/1 [00:00<?, ?it/
DAPI:   0%|                                                               | 0/3 [00:00<?, ?it/s]
T:   0%|                                                                     | 0/1 [00:00<?, ?it/s]
Z:   0%|                                                                     | 0/1 [00:00<?, ?it/s]
```

The images open in ImageJ using the OlympusViewer but I want to batch convert and this tool might be most useful. Thanks.

**Comment by pskeshu** [comment]
Is it possible for you to send these files to me? Dropbox or Google Drive. That would help me troubleshoot the issue.

**Comment by bgriffen** [comment]
Sure - thanks for helping out. I've attached an example image to [this link](https://drive.google.com/drive/folders/17R9TH8zieCHY73Ri737eU0SCQ6EGy6SN?usp=sharing). It contains the vsi file and ets file acquire from the system.

**Comment by pskeshu** [comment]
I have tested with your files, and microscoper appears to be performing slowly, but it ends up generating the TIF files. It took about 54s in my computer (64G RAM, Intel Core i7-6700K @ 8x 4.2GHz). Perhaps you can try to run the tool for a little longer? 

I see that the performance is affected because of the size of the images - they're about 368MB/channel. I'm assuming that it's because you have stitched multiple images into one in CellSense. Is there any reason why you would want that instead of storing individual fields separately? It would also be more efficient (in terms of performance) to process images that are not stitched.

Meanwhile, I will see if performance can be improved for your use case. :)

**Comment by bgriffen** [comment]
Thanks for getting back to me. I've tried it on my Macbook and it looks like it is hanging. I've left it for a few hours and the progress bar doesn't update and looks like I posted above. I then tried my Ubuntu 16.04 node and although it installs in my anaconda python2.7 environment, I get a segmentation fault when running the canonical `python -m microscoper -f .`

```
\OpenBLAS blas_thread_init: pthread_create: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1031176 current, 1031176 max
OpenBLAS blas_thread_init: pthread_create: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1031176 current, 1031176 max
OpenBLAS blas_thread_init: pthread_create: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1031176 current, 1031176 max
OpenBLAS blas_thread_init: pthread_create: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1031176 current, 1031176 max
OpenBLAS blas_thread_init: pthread_create: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1031176 current, 1031176 max
OpenBLAS blas_thread_init: pthread_create: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1031176 current, 1031176 max
OpenBLAS blas_thread_init: pthread_create: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1031176 current, 1031176 max
OpenBLAS blas_thread_init: pthread_create: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1031176 current, 1031176 max
OpenBLAS blas_thread_init: pthread_create: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1031176 current, 1031176 max
OpenBLAS blas_thread_init: pthread_create: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1031176 current, 1031176 max
OpenBLAS blas_thread_init: pthread_create: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1031176 current, 1031176 max
OpenBLAS blas_thread_init: pthread_create: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1031176 current, 1031176 max
OpenBLAS blas_thread_init: pthread_create: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1031176 current, 1031176 max
OpenBLAS blas_thread_init: pthread_create: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1031176 current, 1031176 max
OpenBLAS blas_thread_init: pthread_create: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1031176 current, 1031176 max
OpenBLAS blas_thread_init: pthread_create: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1031176 current, 1031176 max
OpenBLAS blas_thread_init: pthread_create: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1031176 current, 1031176 max
OpenBLAS blas_thread_init: pthread_create: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1031176 current, 1031176 max
OpenBLAS blas_thread_init: pthread_create: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1031176 current, 1031176 max
OpenBLAS blas_thread_init: pthread_create: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1031176 current, 1031176 max
OpenBLAS blas_thread_init: pthread_create: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1031176 current, 1031176 max
Traceback (most recent call last):
  File "/home/bgriffen/anaconda3/envs/py27/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/home/bgriffen/anaconda3/envs/py27/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "/home/bgriffen/anaconda3/envs/py27/lib/python2.7/site-packages/microscoper/__init__.py", line 1, in <module>
    from .io import run
  File "/home/bgriffen/anaconda3/envs/py27/lib/python2.7/site-packages/microscoper/io.py", line 13, in <module>
    import bioformats as bf
  File "/home/bgriffen/anaconda3/envs/py27/lib/python2.7/site-packages/bioformats/__init__.py", line 21, in <module>
    import javabridge
  File "/home/bgriffen/anaconda3/envs/py27/lib/python2.7/site-packages/javabridge/__init__.py", line 38, in <module>
    from .jutil import start_vm, kill_vm, vm, activate_awt, deactivate_awt
  File "/home/bgriffen/anaconda3/envs/py27/lib/python2.7/site-packages/javabridge/jutil.py", line 18, in <module>
    import numpy as np
  File "/home/bgriffen/.local/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/home/bgriffen/.local/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/bgriffen/.local/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/home/bgriffen/.local/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/home/bgriffen/.local/lib/python2.7/site-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
KeyboardInterrupt
Segmentation fault (core dumped)
```

Have you seen this behavior before? Also, could you provide your environment file to check my version of numpy etc. are the same? I'm on `numpy 1.11.3`. I've even tried on a fresh python=2.7 environment followed by `pip install microscoper` with no luck.

**Comment by pskeshu** [comment]
```javabridge==1.0.15
numpy==1.13.3
python-bioformats==1.3.2
tifffile==0.12.1
tqdm==4.19.5
```
```
Python 3.6.4 (default, Jan  5 2018, 02:35:40) 
[GCC 7.2.1 20171224] on linux
```

I think something might be off with your numpy installation. Could you try [building numpy from source](https://docs.scipy.org/doc/numpy/user/building.html) instead of installing through pip?
