### ISSUE TITLE
Exception in thread "Thread-0" java.lang.NoSuchMethodError: setLevel

### ISSUE THREAD

**Issue by n0542344** [pskeshu/microscoper#5]
I'm trying to use microscoper (which sounds exactly like the tool I'd need, since I have to convert multiple .vsi-files into a usable image-format like .tiff or .png or .jpg) but have to admit that I'm unable to do so. 

I'm running `microscoper -f . -k .vsi` in a directory where only the image files are present.

The output of `ls -l` is:

    total 596K
    drwx------ 1 me me   12 2020-07-22 13:23 _30-005 cre_
    -rw------- 1 me me 596K 2020-07-22 13:23 30-005 cre.vsi

The output of `tree -a` is:
     .
     ├── _30-005 cre_
     │   └── stack1
     │       └── frame_t.ets
     └── 30-005 cre.vsi
    
    2 directories, 2 files

    Exception in thread "Thread-0" java.lang.NoSuchMethodError: setLevel
    Traceback (most recent call last):
      File "/home/x0ff/.local/bin/microscoper", line 10, in <module>
        sys.exit(run())
      File "/home/x0ff/.local/lib/python3.7/site-packages/microscoper/io.py", line 185, in run
        logger = _init_logger()
      File "/home/x0ff/.local/lib/python3.7/site-packages/microscoper/io.py", line 162, in _init_logger
        logLevel)
      File "/home/x0ff/.local/lib/python3.7/site-packages/javabridge/jutil.py", line 888, in call
        fn = make_call(o, method_name, sig)
      File "/home/x0ff/.local/lib/python3.7/site-packages/javabridge/jutil.py", line 851, in make_call
        raise JavaException(jexception)
    javabridge.jutil.JavaException: setLevel

Then the process hangs and I have to `Ctrl-C` out of it.

Do you have any ideas why that happens and what I could do to get the program to work properly?

Thanks, Alex

**Comment by pskeshu** [comment]
Can you tell me which version of python-bioformats and python-javabridge
you have in your system?

**Comment by n0542344** [comment]
>Can you tell me which version of python-bioformats and python-javabridge
>you have in your system?


The result of `pip3 show python-bioformats` yields `Version: 1.5.2`.

`pip3 show python-javabridge` gets no results, but `pip3 show
javabridge` gives as output `Version: 1.0.19`.


In the meantime I also installed `bioformats` (without the 'python-'-part),
`pip3 show bioformats` shows `Version: 0.1.15`.  Now my error output of
`microscoper -f . -k .vsi` changed: 


    Traceback (most recent call last):
      File "/home/x0ff/.local/bin/microscoper", line 10, in <module>
        sys.exit(run())
      File "/home/x0ff/.local/lib/python3.7/site-packages/microscoper/io.py", line 184, in run
        jb.start_vm(class_path=bf.JARS, max_heap_size="2G")
    AttributeError: module 'bioformats' has no attribute 'JARS'


and the program exits with an `echo $?` of `1`.

**Comment by n0542344** [comment]
>Can you tell me which version of python-bioformats and python-javabridge
>you have in your system?


The result of `pip3 show python-bioformats` yields `Version: 1.5.2`.

`pip3 show python-javabridge` gets no results, but `pip3 show javabridge` gives as output `Version: 1.0.19`.


In the meantime I also installed `bioformats` (without the 'python-'-part), `pip3 show bioformats` shows `Version: 0.1.15`.  Now my error output of `microscoper -f . -k .vsi` changed: 


    Traceback (most recent call last):
      File "/home/x0ff/.local/bin/microscoper", line 10, in <module>
        sys.exit(run())
      File "/home/x0ff/.local/lib/python3.7/site-packages/microscoper/io.py", line 184, in run
        jb.start_vm(class_path=bf.JARS, max_heap_size="2G")
    AttributeError: module 'bioformats' has no attribute 'JARS'


and the program exits with an `echo $?` of `1`.


ps.: I just re-wrote my answer because I realized that email-replies do not support markdown formatting.
